export interface Lesson {
  id: string;
  title: string;
  description: string;
  createdAt: string;
  thumbnailUrl?: string; // If undefined, we show a default icon
  videoUrl?: string; // Generated video URL
  steps?: string[]; // Textual steps generated by Gemini
}

export interface User {
  name: string;
  email: string;
  avatarUrl: string;
}

export enum AppRoute {
  LOGIN = '/',
  WELCOME = '/welcome',
  DASHBOARD = '/dashboard',
  UPLOAD = '/upload',
  PLAYER = '/player/:id',
  SETTINGS = '/settings'
}